name: MacOSX
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Setup VNC Server (#1)

      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
    - name: Setup VNC server (#2)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
    - name: Setup VNC server (#3)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw vncpass
    - name: Setup VNC server (#4)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
    - name: Setup VNC server (#5)
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
    - name: Install ngrok
      run: brew install ngrok/ngrok/ngrok
    - name: Setup user

      run: sudo dscl . -create /Users/user ;  sudo dscl . -create /Users/user UserShell /bin/bash ; sudo dscl . -create /Users/user RealName “Your name” ; sudo dscl . -create /Users/user UniqueID 1001 ;  sudo dscl . -create /Users/user PrimaryGroupID 1000 ; sudo dscl . -create /Users/user NFSHomeDirectory /Local/Users/user ; sudo dscl . -passwd /Users/user password ; sudo dscl . -append /Groups/admin GroupMembership user
    - name: Set up ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
    - name: Run ngrok
      run: ngrok tcp 5900 &
    - name: ngrok is now listening to VNC connections on...
      run: curl http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
